YOUTUBE_CLONE/YOUTUBE_CLONE/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
from stream_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('login_app.urls')),
    path('stream/',include('stream_app.urls')),
    path("",views.home,name="home")
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

YOUTUBE_CLONE/login_app/urls.py
from django.urls import path
from . import views

app_name = "login_app"

urlpatterns = [
    path('signup/',views.sign_up,name="signup"),
    path('login/',views.login_page,name="login"),
    path('profile/',views.profile,name="profile"),
    path('logout/',views.logout_user,name="logout"),
    path('profile/edit/',views.edit_profile,name="edit"),

    
]

YOUTUBE_CLONE/stream_app/urls.py
from django.urls import path
from . import views

app_name = "stream_app"

urlpatterns = [
    path("",views.home,name="home"),
    path('video-detail/<slug:slug>/',views.details,name='video_details'),
    path('upload-video',views.upload_video,name='upload_video'),
    path('edit-video/<slug:slug>',views.edit_video,name="edit_video"),

    
]

YOUTUBE_CLONE/templates/base.html
<html>
    <head>
        <title> {% block title_block %} Social {% endblock %} </title>
        
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css2?family=Anton&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
        <link href="https://unpkg.com/video.js/dist/video-js.min.css" rel="stylesheet">
        <script src="https://unpkg.com/video.js/dist/video.min.js"></script>
            {% block css_block %}
            {% endblock %}

        

    </head>

    <body>
    
    
        <center>
            <div class="logo display-1"  style="font-family: 'Pacifico', cursive;">
                Youtube
            </div>
            <br>
            <br>
            <blockquote class="blockquote">
                
                <footer class="blockquote-footer">Express Yourself </footer>
            </blockquote>
        </center>
        <div class="container" style="padding-top:30px">
            {% block body_block %}
            {% endblock %}
        </div>


    <div class="footer">
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>   
    </div>
    </body>
</html>

YOUTUBE_CLONE/templates/nav.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
    <title>{% block title_block %} Social {% endblock %}</title>
    {% block css_block %}

    {% endblock %}
  </head>
  <body>
    <!-- navbar section -->
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'stream_app:home' %}">Youtube</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login_app:logout' %}">Log out</a>
          </li>
          <li class="nav-item">
            {% if user.profile.profile_picture %}
            <a class="nav-link" href="{% url 'login_app:profile' %}"><img src="/media/{{user.profile.profile_picture}}" alt="" width="23px" height="23px" class="rounded-circle">{{user.username}}</a>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'stream_app:upload_video' %}">Upload</a>
            </li>
            {% else %}
            <a class="nav-link" href="{% url 'login_app:profile' %}"><img src="/static/images/unisex_avatar.jpg" width="23px" height="23px" class="rounded-circle" alt="default">{{user.username}}</a>
            {% endif %}   
          </li>

         
        </ul>
        <form class="form-inline my-2 my-lg-0" method="GET">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
    <div class="container" style='padding-top:20px'>
    {% block body_block %} {% endblock %}
  </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>