YOUTUBE_CLONE/YOUTUBE_CLONE/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
from stream_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('login_app.urls')),
    path('stream/',include('stream_app.urls')),
    path("",views.home,name="home")
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

YOUTUBE_CLONE/login_app/urls.py
from django.urls import path
from . import views

app_name = "login_app"

urlpatterns = [
    path('signup/',views.sign_up,name="signup"),
    path('login/',views.login_page,name="login"),
    path('profile/',views.profile,name="profile"),
    path('logout/',views.logout_user,name="logout"),
    path('profile/edit/',views.edit_profile,name="edit"),

    
]

YOUTUBE_CLONE/stream_app/urls.py
from django.urls import path
from . import views

app_name = "stream_app"

urlpatterns = [
    path("",views.home,name="home"),
    path('video-detail/<slug:slug>/',views.details,name='video_details'),
    path('upload-video',views.upload_video,name='upload_video'),
    path('edit-video/<slug:slug>',views.edit_video,name="edit_video"),

    
]

YOUTUBE_CLONE/login_app/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    ''' Describe the Profile Model here '''
    user            = models.OneToOneField(User,on_delete=models.CASCADE,related_name="profile")
    profile_picture = models.ImageField(upload_to="display_pictures",blank=True)
    about           = models.CharField(blank=True,max_length=100)
    full_name       = models.CharField(max_length=255,blank=True)
    website         = models.URLField(blank=True)

    def __str__(self):
        return self.user.username
        
         

YOUTUBE_CLONE/login_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from .models import Profile


class SignupForm(UserCreationForm):
    username   = forms.CharField(required=True,label="",widget=forms.TextInput(attrs={'placeholder':'username'}))
    email      = forms.EmailField(required=True,label="",widget=forms.TextInput(attrs={'placeholder':'Enter Email'}))
    password1  = forms.CharField(required=True,label="",widget=forms.PasswordInput(attrs={'placeholder':'Enter Password'}))
    password2  = forms.CharField(required=True,label="",widget=forms.PasswordInput(attrs={'placeholder':'Confirm Password'}))


    model = User
    fields = ('username','email','password1','password2')



class LoginForm(AuthenticationForm):
    username   = forms.CharField(required=True,label="",widget=forms.TextInput(attrs={'placeholder':'username'}))
    password   = forms.CharField(required=True,label="",widget=forms.PasswordInput(attrs={'placeholder':'password'}))

    class Meta:
        model  = User
        fields = ['username','password']



## profile model edit functionality
class EditProfile(forms.ModelForm):
    class Meta:
        model   = Profile
        exclude = ['user'] 
    

YOUTUBE_CLONE/login_app/views.py
from django.shortcuts import render,HttpResponse,HttpResponseRedirect
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from .forms import SignupForm,LoginForm,EditProfile
from .models import Profile


def sign_up(request):
    form = SignupForm()
    if request.method == "POST":
        form = SignupForm(data = request.POST)
        if form.is_valid():
            ## save the model and get the user from the form
            user = form.save()
            ## add the user_profile the user
            user_profile = Profile(user=user)
            user_profile.save()
            return HttpResponseRedirect(reverse("login_app:login"))
            #return HttpResponseRedirect(reverse('login_app:login'))
    return render(request,'login_app/signup.html',{'form':form})

def login_page(request):
    form = LoginForm()
    if request.method == "POST":
        form = LoginForm(data = request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user     = authenticate(username=username,password=password)
            if user is not None:
                login(request,user)
                #return HttpResponse("You are logged in")
                return HttpResponseRedirect(reverse('stream_app:home'))
    
    return render(request,'login_app/login.html',{'form':form})


@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('login_app:login'))

@login_required
def profile(request):
    return render(request,'login_app/profile.html',{})

@login_required
def edit_profile(request):
    ## fetch the current users profile objects
    current_user_profile = Profile.objects.get(user=request.user)
    form = EditProfile(instance=current_user_profile)
    if request.method == "POST":
        form = EditProfile(request.POST,request.FILES,instance=current_user_profile)
        if form.is_valid():
            form.save()
            ## reset the form
            form = EditProfile(instance=current_user_profile)
            return HttpResponseRedirect(reverse('stream_app:home'))
    return render(request,'login_app/edit_profile.html',{'form':form})
            

YOUTUBE_CLONE/templates/login_app/edit_profile.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_block %} Signup {% endblock %}

{% block css_block %}

{% endblock %}


{% block body_block %}
<center>
        
    <div class="signup">
        <h1 class="display-4">Edit Profile</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <input type="submit" class="btn btn-outline-info" style="width:100%" value="Edit Profile">
        </form>
        <div>
            <p>Go to profile <a href="{% url 'login_app:profile' %}"> profile </a></p>
        </div>
    </div>
</center>


{% endblock %}

YOUTUBE_CLONE/templates/login_app/login.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_block %} Signup {% endblock %}

{% block css_block %}

{% endblock %}


{% block body_block %}
<center>
        
    <div class="signup">
        <h1 class="display-4">Login</h1>
        <form method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <input type="submit" class="btn btn-outline-info" style="width:100%" value="Signup">
        </form>
        <div>
            <p>Dont Have An Account? <a href="{% url 'login_app:signup' %}"> Signup </a></p>
        </div>
    </div>
</center>


{% endblock %}

YOUTUBE_CLONE/templates/login_app/profile.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_block %}profile @{{user}}{% endblock %}
{% block css_block %}
        <style>
        .crop {
            width: 300px;
            height: 300px;
            overflow: hidden;
        }

        .crop img {
            border: 5px solid #ddd;
            border-radius: 9px;
            padding: 7px;
            width: 300px;

        div.polaroid {
            width: 80%;
            background-color: white;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            margin-bottom: 25px;
    }
  }

        </style>

{% endblock %}
{% block body_block %}
        <div class="row" style="font-family: 'Pacifico', cursive;">
            <div class="col-sm-4">
            {% if user.profile.profile_picture %}
                <img src="/media/{{user.profile.profile_picture}}" width="250px" height="250px" class="rounded-circle">
            {% else %}
                <img src="/media/default.png" width="250px" height="250px" class="rounded-circle">
            {% endif %}
            </div>
        
        </div>
        <div class="col-sm-8 container">
            <center>
                <h1 style="font-family: 'Yanone Kaffeesatz', sans-serif;">{{user.profile}}</center><a href="{% url 'login_app:edit'%}" class="btn btn-outline-success btn-lg">Edit Profile</a></h1>
            
            <br> 
            <br>
            <h4 style="font-family: 'Pacifico', cursive;">Full name : {{user.profile.full_name}} </h4>
            <br>
            <p style="font-family: 'Pacifico', cursive;" > {{ user.profile.about }}</p>
            <p style="font-family: 'Pacifico', cursive;" > Website :  {{ user.profile.website }}</p>
            
            <br>
            
        
          </div>
        </div>
        <hr>

        <div class="my-videos">
            <div class="row p-5">
                {% for video in user.post_user.all %}
                <div class="col-sm-6">
                    <a href="{% url 'stream_app:video_details' slug=video.slug %}"><img src="/media/{{video.thumbnail}}" alt="" width="100"></a><br>
                    <Strong>{{video.video_title}}</Strong> <br>
                    <small class="text-muted"><strong>Publish date: </strong>{{video.publish_date}}</small><br>
                    <small class="text-muted"><strong>Updated on: </strong>{{video.update_date}}</small> <br>
                    <b>{{video.video_comment.count}} Comments</b> &nbsp; 
                    <a href="{% url 'stream_app:edit_video' slug=video.slug %}" class="btn btn-secondary btn-sm">Edit Video</a>
                </div>
                {% endfor %}
            </div>
        </div>


{% endblock %}

YOUTUBE_CLONE/templates/login_app/signup.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_block %} Signup {% endblock %}

{% block css_block %}

{% endblock %}


{% block body_block %}
<center>
        
    <div class="signup">
        <h1 class="display-4">SignUp</h1>
        <form method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <input type="submit" class="btn btn-outline-info" style="width:100%" value="Signup">
        </form>
        <div>
            <p>Already Have An Account? <a href="{% url 'login_app:login' %}"> Login </a></p>
        </div>
    </div>
</center>


{% endblock %}